// ----------------------------------------------
// ✨ Only Comments below are generated by ChatGPT ✨
// ----------------------------------------------

// Import quiz data from external file
import { quizData } from "./data.js";

// Initialize score counter
let correctAnswerCount = 0;

// Select the main container from the DOM
const mainContainer = document.querySelector(".main-container");

// Start the quiz when the page is fully loaded
document.addEventListener("DOMContentLoaded", () => {
  let currentQuestionIndex = 0;
  renderQuestion(currentQuestionIndex);
});

// Main function to render current question
function renderQuestion(currentQuestionIndex) {
  quizData.forEach((eachQuiz, index) => {
    if (index == currentQuestionIndex) {
      createQuestionCard(eachQuiz, index, currentQuestionIndex);
    }
  });

  // If user has answered all questions, show final result
  if (currentQuestionIndex == quizData.length) {
    showFinalResult(quizData);
  }
}

// Function to display final result
function showFinalResult(quizData) {
  const ans = `You answered ${correctAnswerCount}/ ${quizData.length}`;
  const para = document.createElement("p");
  para.innerText = ans;
  mainContainer.appendChild(para);
}

// Function to create and display a single question card
function createQuestionCard(eachQuiz, currentQuestionIndex) {
  const quizCard = document.createElement("div");
  quizCard.classList.add("quiz-container");

  // Dynamically creating question and options
  quizCard.innerHTML = `
    <h3>${eachQuiz.question}</h3>
    <div class="options-wrapper">
      <div class="option-container">
        <input type="radio" id="a" name="language" />
        <label for="a">${eachQuiz.a}</label>
      </div>
      <div class="option-container">
        <input type="radio" id="b" name="language" />
        <label for="b">${eachQuiz.b}</label>
      </div>
      <div class="option-container">
        <input type="radio" id="c" name="language" />
        <label for="c">${eachQuiz.c}</label>
      </div>
      <div class="option-container">
        <input type="radio" id="d" name="language" />
        <label for="d">${eachQuiz.d}</label>
      </div>
    </div>
  `;

  // Attach Next button along with quizCard
  attachNextButton(quizCard, currentQuestionIndex, eachQuiz);
}

// Function to attach the "Next" button and handle click event
function attachNextButton(quizCard, currentQuestionIndex, eachQuiz) {
  const nextButton = document.createElement("button");
  nextButton.classList.add("next-button");
  nextButton.textContent = "Next";

  mainContainer.appendChild(quizCard);
  mainContainer.appendChild(nextButton);

  // Event listener for "Next" button click
  nextButton.addEventListener("click", () => {
    currentQuestionIndex++;

    // Check user's selected answer
    let selectedOption = checkAnswer(eachQuiz);

    if (selectedOption) {
      // Remove old question card and button
      mainContainer.removeChild(quizCard);
      mainContainer.removeChild(nextButton);

      // Render next question
      renderQuestion(currentQuestionIndex);
    }
  });
}

// Function to check if the selected answer is correct
function checkAnswer(eachQuiz) {
  const selectedOption = document.querySelector(
    'input[name="language"]:checked'
  );

  if (selectedOption) {
    if (selectedOption.id === `${eachQuiz.correct}`) {
      correctAnswerCount++;
    }
  } else {
    alert("Select one option");
    return;
  }

  return selectedOption;
}
